import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faMobileAlt,
  faLaptop,
  faHeadphones,
  faClock,
  faVolumeUp,
  faPlug,
  faCalculator,
  faBatteryFull,
  faBook,
  faBucket,
  faPencilRuler,
  faDraftingCompass,
  faMicroscope,
  faBed,
  faChair,
  faTable,
  faLightbulb,
  faAlignJustify,
  faTshirt,
  faShoePrints,
  faShoppingBag,
  faUserTie,
  faHatCowboy,
  faStopwatch,
  faBaseballBall,
  faFootballBall,
  faTableTennis,
  faDumbbell,
  faBicycle,
  faMotorcycle,
  faSkating,
  faHelmetSafety,
  faLock,
} from "@fortawesome/free-solid-svg-icons";

const TYPES = {
  "Electronics & Gadgets": [
    { id: 1, name: "Mobile", icon: faMobileAlt },
    { id: 2, name: "Laptop", icon: faLaptop },
    { id: 3, name: "Headphones", icon: faHeadphones },
    { id: 4, name: "Smartwatch", icon: faClock },
    { id: 5, name: "Speakers", icon: faVolumeUp },
    { id: 6, name: "Charger", icon: faPlug },
    { id: 7, name: "Calculator", icon: faCalculator },
    { id: 8, name: "Power Bank", icon: faBatteryFull },
  ],
  "Study Essentials": [
    { id: 1, name: "Textbooks", icon: faBook },
    { id: 2, name: "Stationery", icon: faPencilRuler },
    { id: 3, name: "Calculator", icon: faCalculator },
    { id: 4, name: "Drawing Instruments", icon: faDraftingCompass },
    { id: 5, name: "Lab Equipment", icon: faMicroscope },
  ],
  "Room & Hostel Stuff": [
    { id: 1, name: "Bed", icon: faBed },
    { id: 2, name: "Mattress", icon: faBed },
    { id: 3, name: "Chair", icon: faChair },
    { id: 4, name: "Table", icon: faTable },
    { id: 5, name: "Lamp", icon: faLightbulb },
    { id: 6, name: "Curtains", icon: faAlignJustify },
    { id: 7, name: "Bucket", icon: faBucket }, // You'll need to import faBucket
  ],
  "Clothing & Accessories": [
    { id: 1, name: "Hoodie", icon: faTshirt },
    { id: 2, name: "Jacket", icon: faTshirt },
    { id: 3, name: "Shoes", icon: faShoePrints },
    { id: 4, name: "Bag", icon: faShoppingBag },
    { id: 5, name: "Belt", icon: faUserTie },
    { id: 6, name: "Cap", icon: faHatCowboy },
    { id: 7, name: "Watch", icon: faStopwatch },
  ],
  "Sports & Fitness": [
    { id: 1, name: "Cricket Bat", icon: faBaseballBall },
    { id: 2, name: "Football", icon: faFootballBall },
    { id: 3, name: "Badminton Racket", icon: faTableTennis },
    { id: 4, name: "Dumbbells", icon: faDumbbell },
    { id: 5, name: "Yoga Mat", icon: faAlignJustify }, // Placeholder, replace if you find yoga icon
  ],
  "Cycles & Transport": [
    { id: 1, name: "Bicycle", icon: faBicycle },
    { id: 2, name: "Scooter", icon: faMotorcycle },
    { id: 3, name: "Skateboard", icon: faSkating },
    { id: 4, name: "Helmet", icon: faHelmetSafety },
    { id: 5, name: "Lock", icon: faLock },
  ],
};

export default TYPES;
